apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hami-mock-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: hami-mock-device-plugin
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        app.kubernetes.io/component: hami-mock-device-plugin
    spec:
      serviceAccountName: hami-mock-device-plugin
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      containers:
      - image: projecthami/mock-device-plugin:latest 
        name: hami-mock-dp-cntr
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        command:
          - ./k8s-device-plugin
          - -v=5
          - --device-config-file=/device-config.yaml
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            drop: ["ALL"]
            add: ["SYS_ADMIN"]
        volumeMounts:
          - name: dp
            mountPath: /var/lib/kubelet/device-plugins
          - name: sys
            mountPath: /sys
          - name: device-config
            mountPath: /device-config.yaml
            subPath: device-config.yaml
      volumes:
        - name: dp
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: sys
          hostPath:
            path: /sys
        - name: device-config
          configMap:
            name: hami-scheduler-device

