apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hami-mock-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: hami-mock-dp-ds
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: hami-mock-dp-ds
    spec:
      serviceAccountName: hami-mock-device-plugin
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      containers:
      - image: projecthami/mock-device-plugin:latest 
        name: hami-mock-dp-cntr
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            drop: ["ALL"]
            add: ["SYS_ADMIN"]
        volumeMounts:
          - name: dp
            mountPath: /var/lib/kubelet/device-plugins
          - name: sys
            mountPath: /sys
      volumes:
        - name: dp
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: sys
          hostPath:
            path: /sys

